const router = require('express').Router();
const { authenticate } = require('../middleware/auth');
const { requireRole } = require('../middleware/roleCheck');
const { rejectIfFormsHubViewOnly } = require('../utils/formsHubViewOnly');
const ctrl = require('../controllers/powerNew.controller');
const hier = require('../controllers/ppnHierarchy.controller');

router.get('/lookup',               authenticate, ctrl.lookupEquipment);
router.get('/hierarchy',            authenticate, hier.getTree);
router.get('/hierarchy/cards',      authenticate, hier.getCards);
router.get('/hierarchy/path/:nodeId', authenticate, hier.getPath);
router.post('/hierarchy',           authenticate, rejectIfFormsHubViewOnly, hier.createNode);
router.post('/hierarchy/move',      authenticate, rejectIfFormsHubViewOnly, hier.moveNodes);
router.get('/hierarchy/stars',      authenticate, hier.listStars);
router.post('/hierarchy/stars',     authenticate, hier.addStarNode);
router.delete('/hierarchy/stars/:nodeId', authenticate, hier.removeStarNode);
router.get('/hierarchy/move-history', authenticate, hier.listMoveHistoryEntries);
router.put('/hierarchy/:nodeId',    authenticate, rejectIfFormsHubViewOnly, hier.updateNode);
router.delete('/hierarchy/:nodeId', authenticate, rejectIfFormsHubViewOnly, hier.deleteNode);
router.patch('/hierarchy/:nodeId/link', authenticate, rejectIfFormsHubViewOnly, hier.linkNode);
router.patch('/hierarchy/:nodeId/sync-name', authenticate, rejectIfFormsHubViewOnly, hier.syncNodeName);
router.get('/',                     authenticate, ctrl.listEquipment);
router.post('/',                    authenticate, rejectIfFormsHubViewOnly, ctrl.createEquipment);
router.get('/:id',                  authenticate, ctrl.getEquipment);
router.put('/:id',                  authenticate, rejectIfFormsHubViewOnly, ctrl.updateEquipment);
router.put('/:id/image/:type',      authenticate, rejectIfFormsHubViewOnly, ctrl.uploadImage);
router.delete('/:id/image/:type',   authenticate, rejectIfFormsHubViewOnly, ctrl.deleteImage);
router.put('/:id/specs',            authenticate, rejectIfFormsHubViewOnly, ctrl.updateSpecs);
router.put('/:id/schedule',         authenticate, rejectIfFormsHubViewOnly, ctrl.updateSchedule);
router.delete('/:id/history-sub-group', authenticate, rejectIfFormsHubViewOnly, ctrl.deleteSubGroupHistory);
router.put('/:id/history-sub-group/rename', authenticate, rejectIfFormsHubViewOnly, ctrl.renameSubGroupHistory);
router.get('/:id/history',          authenticate, ctrl.getHistory);
router.post('/:id/history',         authenticate, rejectIfFormsHubViewOnly, ctrl.addHistory);
router.put('/:id/history/:hid',     authenticate, rejectIfFormsHubViewOnly, ctrl.updateHistory);
router.delete('/:id/history/:hid',  authenticate, requireRole('admin'), rejectIfFormsHubViewOnly, ctrl.deleteHistory);
router.post('/:id/history/:hid/documents', authenticate, rejectIfFormsHubViewOnly, ctrl.uploadHistoryDocumentMiddleware, ctrl.uploadHistoryDocument);
router.post('/:id/history-approval/:requestId/documents', authenticate, rejectIfFormsHubViewOnly, ctrl.uploadApprovalDocumentMiddleware, ctrl.uploadApprovalDocument);
router.delete('/:id/history-approval/:requestId/documents/:fileName', authenticate, rejectIfFormsHubViewOnly, ctrl.deleteApprovalDocument);
router.get('/:id/history/:hid/documents/:fileName', authenticate, ctrl.downloadHistoryDocument);

module.exports = router;
