// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { createRequire } from "node:module";
import { defineConfig } from "prisma/config";

const require = createRequire(import.meta.url);
const { resolveDatabaseUrl } = require("./config/databaseName") as {
  resolveDatabaseUrl: (env?: NodeJS.ProcessEnv) => string;
};

const databaseUrl = resolveDatabaseUrl() || process.env["DATABASE_URL"] || "";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
