/** Parsed from PHReport_Stoppages.html */

export const PH_STOPPAGE_SECTION_OPTIONS = [
  "",
  "150 TPH Boiler",
  "30.85 MW Turbine",
  "35 TPH Boiler",
  "35 TPH Boiler & 4MW Turbine",
  "4MW Turbine",
  "70TPH Boiler",
  "3MW Turbine (Old)",
  "3MW Turbine (New)",
  "Grid",
  "Others"
];

export const PH_STOPPAGE_SUBSECTION_OPTIONS = [
  "",
  "MILL - GENERAL CLEANING",
  "BOILER FEED WATER STATION",
  "FURNACE",
  "BOILER FANS",
  "BAGASSE FEEDING SYSTEM",
  "FUEL HANDLING SYSTEM",
  "ASH HANDLING SYSTEM",
  "SHOOT BLOWER SYSTEM",
  "TURBINE & GENERATOR",
  "OIL PUMP",
  "CONDENSATE SYSTEM",
  "COOLING WATER SYSTEM",
  "110 VDC SYSTEM",
  "DCS & UPS",
  "132 KV SWITCHYARD",
  "132 KV TRANSMISSION LINE",
  "Service Air",
  "Converter Transformer",
  "Switch yard",
  "OTHERS"
];

export const PH_STOPPAGE_MACHINERY_OPTIONS = [
  "",
  "N/A",
  "Feed Water Pump-A",
  "Feed Water Pump-B",
  "Feed Water Pump-C",
  "Feed Water Pump-D",
  "30% Control Valve",
  "100% Control Valve",
  "Deaerator",
  "H.P. Heater-1",
  "H.P. Heater-2",
  "Hydraulic Drive-1",
  "Hydraulic Drive-2",
  "Travelling Grate",
  "Furnace Tubes",
  "ID Fan-A",
  "ID Fan-B",
  "FD Fan-A",
  "FD Fan-B",
  "SA Fan-A",
  "SA Fan-B",
  "Screw Feeder-1",
  "Screw Feeder-2",
  "Screw Feeder-3",
  "Screw Feeder-4",
  "Screw Feeder-5",
  "Drum Feeder-1",
  "Drum Feeder-2",
  "Drum Feeder-3",
  "Drum Feeder-4",
  "Drum Feeder-5",
  "RAD- 1 & 2",
  "RPG gate 1 to 5",
  "Belt Conveyor-1 (BC-1)",
  "Belt Conveyor-2 (BC-2)",
  "Belt Conveyor-3 (BC-3)",
  "Belt Conveyor-4 (BC-4)",
  "Belt Conveyor-5 (BC-5)",
  "Belt Conveyor-6 (BC-6)",
  "Belt Conveyor-7 (BC-7)",
  "Belt Conveyor-8 (BC-8)",
  "Bagasse Elevator",
  "Slat chain Conveyor",
  "Submerged Belt Conveyor",
  "Magnetic Seprator-1",
  "Magnetic Seprator-2",
  "RPG Gate at BC-1",
  "Flap Gate",
  "BC-5 Electrical Actuator (Plough)",
  "New Belt Conveyor-1 (NBC-1)",
  "New Belt Conveyor-2 (NBC-2)",
  "New Belt Conveyor-3 (NBC-3)",
  "New Belt Conveyor-4 (NBC-4)",
  "New Belt Conveyor-5 (NBC-5)",
  "New Belt Conveyor-6 (NBC-6)",
  "New Belt Conveyor-7 (NBC-7)",
  "Magnetic Separator at NBC-5",
  "ESP Transformer - 1",
  "ESP Transformer - 2",
  "ESP Transformer - 3",
  "ESP Transformer - 4",
  "Ash Handling System-1 (APH Master)",
  "Ash Handling System-1 (APH Slave)",
  "Ash Handling System-2 (ESP 1st Field)",
  "Ash Handling System-3 (ESP 2nd Field)",
  "Ash Handling System-4 (ESP 3rd Field)",
  "Ash Handling System-4 (ESP 4th Field)",
  "Ash Silo",
  "Purging Air System",
  "LRSB-1",
  "LRSB-2",
  "LRSB-3",
  "LRSB-4",
  "LRSB-5",
  "LRSB-6",
  "RSB-1",
  "RSB-2",
  "RSB-3",
  "RSB-4",
  "RSB-5",
  "RSB-6",
  "RSB-7",
  "RSB-8",
  "RSB-9",
  "RSB-10",
  "RSB-11",
  "RSB-12",
  "RSB-13",
  "RSB-14",
  "RSB-15",
  "RSB-16",
  "RSB-17",
  "RSB-18",
  "HP Actuator",
  "LP Actuator",
  "Governing Valve",
  "Grid Valve",
  "Emergency Stop Valve (ESV)",
  "Barring Gear",
  "Turbine Front & Rear side",
  "Gear Box Pinion",
  "Gear Box Gear",
  "Generator front & Rear",
  "HT Busbar",
  "Exciter",
  "RRA",
  "PMG",
  "Metering and Synch.Panel",
  "Protection Panel",
  "AVR Panel",
  "Vibration System",
  "Temp. Monitoring System",
  "Governor System",
  "Overspeed Trip System",
  "Emergency Oil Pump (EOP)",
  "Auxillery Oil Pump-1 (AOP-1)",
  "Auxillery Oil Pump-2 (AOP-2)",
  "Auxillery Control Oil Pump-1 (ACOP-1)",
  "Auxillery Control Oil Pump-2 (ACOP-2)",
  "Jacking Oil Pump-1 (JOP-1)",
  "Jacking Oil Pump-2 (JOP-2)",
  "MCW Pump - A",
  "MCW Pump - B",
  "MCW Pump - C",
  "CEP Pump - A",
  "CEP Pump - B",
  "CEP Pump - C",
  "Vacuum Breaker MOV",
  "Ejector System",
  "GVC System",
  "Hotwell Level Transmitter",
  "30% Level Control Valve",
  "100% Level Control Valve",
  "Cooling Tower",
  "Aux. Cooling Water Pump-A",
  "Aux. Cooling Water Pump-B",
  "Aux. Cooling Water Pump-C",
  "CT Fan-A",
  "CT Fan-B",
  "Battery Bank",
  "Battery Charger",
  "DC DB",
  "Boiler DCS System",
  "Turbine DCS System",
  "WTP DCS System",
  "Server-1",
  "Server-2",
  "Operating System 1 TO 6",
  "UPS Set-1 (20 KVA)",
  "UPS Set-2 (5 KVA)",
  "Battery Bank (20 KVA)",
  "Battery Bank (5 KVA)",
  "Power Transformer  , Rating - 31.5/40MVA",
  "Power Transformer OLTC",
  "SF-6 Breaker",
  "R- Phase CT",
  "Y- Phase CT",
  "B- Phase CT",
  "R- Phase PT",
  "Y- Phase PT",
  "B- Phase PT",
  "Line Side Lightning arrester",
  "Power Transformer side Lightning arrester",
  "Line Side Isolator",
  "Power Transformer Side Isolator",
  "OD VCB",
  "Protection Panel",
  "OLTC Control Panel",
  "Transmission Line",
  "Sub-Station",
  "Feed Storage Tank",
  "Feed Transfer Pump No-1",
  "Feed Transfer Pump No-2",
  "DM Water Storage Tank",
  "DM Water Transfer Pump No-1",
  "DM Water Transfer Pump No-2",
  "Hydraulic Drive",
  "Furnace Tubes",
  "Water Wall Panel",
  "ID Fan",
  "FD Fan",
  "SA Fan",
  "RAD",
  "RPG Gate 1 to 3",
  "Dist Belt Conveyor-1 (DBC-1)",
  "Dist Belt Conveyor-2 (DBC-2)",
  "Dist Belt Conveyor-3 (DBC-3)",
  "Dist Belt Conveyor-4 (DBC-4)",
  "Dist Belt Conveyor-5 (DBC-5)",
  "Dist Belt Conveyor-6 (DBC-6)",
  "Dist Slat chain Conveyor (DSC)",
  "Magnetic Separator",
  "Water Cooled Ash Screw Conv-1",
  "Water Cooled Ash Screw Conv-2",
  "Bag Filter Ash Screw Conv-3",
  "Bag Filter Ash Screw Conv-4",
  "Ash Handling System -1 (Super Heater)",
  "Ash Handling System -2 (Evaporator)",
  "Ash Handling System -3 (Economiser)",
  "Ash Handling System-4 (Bag Filter)",
  "Ash Handling System-5 (Bag Filter)",
  "RAV No-1",
  "RAV No-2",
  "RAV No-3",
  "RAV No-4",
  "RAV No-5",
  "RAV No-6",
  "Ash Handling Comp No-1",
  "Ash Handling Comp No-2",
  "Instrument Air Comp No-1",
  "Instrument Air Comp No-2",
  "Instrument Air Comp No-3",
  "Servicer Air Storage Tank",
  "Dryer",
  "Wall Blower-01",
  "Wall Blower-02",
  "Wall Blower-03",
  "Wall Blower-04",
  "Wall Blower-05",
  "Wall Blower-06",
  "Wall Blower-07",
  "Wall Blower-08",
  "Wall Blower-09",
  "Wall Blower-10",
  "Wall Blower-11",
  "Wall Blower-12",
  "Wall Blower-13",
  "Wall Blower-14",
  "Wall Blower-15",
  "Wall Blower-16",
  "Wall Blower-17",
  "Wall Blower-18",
  "Wall Blower-19",
  "Wall Blower-20",
  "Generator",
  "HT Switch Gear Panel & Busbar",
  "Metering and Synch Panel",
  "LAVT and NGR Panel",
  "Over speed Trip System",
  "Auxiliary Oil Pump (AOP)",
  "Booster Control Oil Pump-1",
  "Booster Control Oil Pump-2",
  "Mechanical Oil Pump (MOP)",
  "CT Fan - A",
  "CT Fan - B",
  "Generator Cooler",
  "Operating System 1 TO 5",
  "UPS Set-1 (15 KVA)",
  "UPS Set-2 (15 KVA)",
  "Battery Bank (15 KVA)",
  "PCC Transformer No-1",
  "VFD Transformer No-2",
  "30MW Power Plant Switch yard",
  "Feed Water Pump-1",
  "Feed Water Pump-2",
  "Feed Water Pump-3",
  "Turbo Feed Water Pump-4",
  "Feed Water Control Valve",
  "Transfer Pump No-01",
  "Transfer Pump No-02",
  "Boiler Feed water storage tank",
  "Dumping grate furnace",
  "Furnace Tubes, Boiler Bank, super Heater & Eco",
  "APH tubes",
  "Super Heater safety valve",
  "Drum safety valve (LHS)",
  "Drum safety valve (RHS)",
  "Main steam stop valve",
  "ID Fan No-01",
  "ID Fan No-02",
  "SA Fan(New)",
  "SA Fan (Old)",
  "Suction Damper-01 (ID Fan-01 )",
  "Suction Damper-02 (ID Fan-02 )",
  "Suction Damper-02 (FD Fan )",
  "Bagasse Drum Feeder-1",
  "Bagasse Drum Feeder-2",
  "Bagasse Drum Feeder-3",
  "Bagasse Drum Feeder-4",
  "Bagasse Drum Feeder-5",
  "Bagasse Drum Feeder-6",
  "RPG gate 1 to 6",
  "Main Bagasse Carrier (MBC)",
  "Return Bagasse Carrier (RBC)",
  "Wet scrubber (LHS)",
  "Wet scrubber (RHS)",
  "Slurry Pump-01",
  "Slurry Pump-02",
  "Slurry Pump-03",
  "Injection pump-01",
  "Injection pump-02",
  "Injection pump-03",
  "Ash Drag conveyor",
  "Rotary Soot Blower No-1",
  "Rotary Soot Blower No-2",
  "Rotary Soot Blower No-3",
  "Rotary Soot Blower No-4",
  "Rotary Soot Blower No-5",
  "Rotary Soot Blower No-6",
  "Rotary Soot Blower No-7",
  "Rotary Soot Blower No-8",
  "Rotary Soot Blower No-9",
  "45/21 KG/CM2 PRDS Control valve",
  "21/14 KG/CM2 PRDS Control valve",
  "14/1 KG/CM2 PRDS Control valve",
  "DSH Control Valves 1 To 4",
  "DSH Nozzles",
  "Desuperheating Pump-1",
  "Desuperheating Pump-2",
  "Manual Isolation valve",
  "DCS Server & Operating System",
  "DCS Controller & IO cards",
  "Others"
];

export const PH_STOPPAGE_CATEGORY_OPTIONS = [
  "",
  "Electrical",
  "Instrumentation",
  "Mechanical",
  "Other"
];
