/** Options from milling_stoppages.html (legacy Milling Logbooks); values persist as readable strings in DB */

export const MILL_STOPPAGE_SECTION_OPTIONS = [
  '',
  'CANE',
  'CANE HANDLING EQUIPMENTS',
  'PREPERATORY DEVICES',
  'MILLS',
  '70TPH BOILER',
  '150TPH BOILER',
  'PROCESS DS',
  'PROCESS RS',
  'BOILING HOUSE',
  'REDUCED JUICE FLOW',
  'OTHERS',
];

export const MILL_STOPPAGE_MACHINERY_OPTIONS = [
  '',
  'N/A',
  'No Cane',
  'Weather',
  'Cane Unloader 1',
  'Cane Unloader 2',
  'Cane Unloader 3',
  'Cane Unloader 4',
  'Cane Unloader 5',
  'Cane Unloader 6',
  'Truck Trippler',
  'Main Cane Carrier',
  'Auxiliary Cane Carrier',
  'Kicker',
  'Carding Drum-1',
  'Carding Drum-2',
  'Feeder Drum',
  'In-line Shredder',
  'Rake Carrier',
  'Cane Belt Conveyor',
  'IRC 1',
  'IRC 2',
  'IRC 3',
  'IRC 4',
  'Slat Cleaning Brush',
  'Cane Equalizer',
  'Zero Mill',
  '1st Mill',
  '2nd Mill',
  '3rd Mill',
  '4th Mill',
  'Mill Turbine 1',
  'Mill Turbine 2',
  'Mill Turbine 3',
  'Transmission Gearing 0',
  'Transmission Gearing 1',
  'Transmission Gearing 2',
  'Transmission Gearing 3',
  'Transmission Gearing 4',
  'Under Feed Roller',
  'Mill Automation System',
  'Zero Mill Unscreen Juice Pump',
  '1st Mill Unscreen Juice Pump',
  '2nd Mill Maceration Juice Pump',
  '3rd Mill Maceration Juice Pump',
  '4th Mill Maceration Juice Pump',
  'Water Imbibition Pump',
  '1st Stage Rotary Screen',
  '2nd Stage Rotary Screen',
  '1st Stage Screening Juice Storage Tank',
  '1st Stage Screening Juice Pump',
  'DS Side Juice Pump',
  'Second Stage Screening Juice',
  'Storage Tank for Refinery',
  'Pump for Refinery',
  'Mag Flow Meter - DS',
  'Mass Flow Meter - DS',
  'Mag Flow Meter - RS',
  'Mass Flow Meter - RS',
  'Mag Flow Meter - Imbibition Water',
  'Mag Flow Meter - Rotary Screen Washing',
  'Boiler - Electrical',
  'Boiler - Instrumentation',
  'Boiler - Mechanical',
  'Boiling House (DS) - Mechanical',
  'Boiling House (RS) - Mechanical',
  'Boiling House (DS) - Electrical',
  'Boiling House (RS) - Electrical',
  'Others',
];
