-- Production Forms — 5 tables

CREATE TABLE IF NOT EXISTS `prod_shift_chemist` (
  `id`                    INT           NOT NULL AUTO_INCREMENT,
  `Date`                  DATE              DEFAULT NULL,
  `season`                VARCHAR(20)       DEFAULT NULL,
  `instructions`          TEXT              DEFAULT NULL,
  `shift8_4_jobs_done`    TEXT              DEFAULT NULL,
  `shift8_4_jobs_todo`    TEXT              DEFAULT NULL,
  `shift8_4_sign`         VARCHAR(100)      DEFAULT NULL,
  `shift4_12_jobs_done`   TEXT              DEFAULT NULL,
  `shift4_12_jobs_todo`   TEXT              DEFAULT NULL,
  `shift4_12_sign`        VARCHAR(100)      DEFAULT NULL,
  `shift12_8_jobs_done`   TEXT              DEFAULT NULL,
  `shift12_8_jobs_todo`   TEXT              DEFAULT NULL,
  `shift12_8_sign`        VARCHAR(100)      DEFAULT NULL,
  `timestamp`             TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `prod_centrifugal` (
  `id`                    INT           NOT NULL AUTO_INCREMENT,
  `Date`                  DATE              DEFAULT NULL,
  `Shift`                 VARCHAR(20)       DEFAULT NULL,
  `shw_temp`              DECIMAL(8,2)      DEFAULT NULL,
  `shw_pressure`          DECIMAL(8,2)      DEFAULT NULL,
  `air_pressure`          DECIMAL(8,2)      DEFAULT NULL,
  `m1_basket_cleaning`    TINYINT(1)        DEFAULT NULL,
  `m1_screen_condition`   VARCHAR(100)      DEFAULT NULL,
  `m1_from`               VARCHAR(10)       DEFAULT NULL,
  `m1_to`                 VARCHAR(10)       DEFAULT NULL,
  `m1_duration`           VARCHAR(20)       DEFAULT NULL,
  `m1_reasons`            TEXT              DEFAULT NULL,
  `m1_separator`          TINYINT(1)        DEFAULT NULL,
  `m1_remarks`            TEXT              DEFAULT NULL,
  `m2_basket_cleaning`    TINYINT(1)        DEFAULT NULL,
  `m2_screen_condition`   VARCHAR(100)      DEFAULT NULL,
  `m2_from`               VARCHAR(10)       DEFAULT NULL,
  `m2_to`                 VARCHAR(10)       DEFAULT NULL,
  `m2_duration`           VARCHAR(20)       DEFAULT NULL,
  `m2_reasons`            TEXT              DEFAULT NULL,
  `m2_separator`          TINYINT(1)        DEFAULT NULL,
  `m2_remarks`            TEXT              DEFAULT NULL,
  `m3_basket_cleaning`    TINYINT(1)        DEFAULT NULL,
  `m3_screen_condition`   VARCHAR(100)      DEFAULT NULL,
  `m3_from`               VARCHAR(10)       DEFAULT NULL,
  `m3_to`                 VARCHAR(10)       DEFAULT NULL,
  `m3_duration`           VARCHAR(20)       DEFAULT NULL,
  `m3_reasons`            TEXT              DEFAULT NULL,
  `m3_separator`          TINYINT(1)        DEFAULT NULL,
  `m3_remarks`            TEXT              DEFAULT NULL,
  `m4_basket_cleaning`    TINYINT(1)        DEFAULT NULL,
  `m4_screen_condition`   VARCHAR(100)      DEFAULT NULL,
  `m4_from`               VARCHAR(10)       DEFAULT NULL,
  `m4_to`                 VARCHAR(10)       DEFAULT NULL,
  `m4_duration`           VARCHAR(20)       DEFAULT NULL,
  `m4_reasons`            TEXT              DEFAULT NULL,
  `m4_separator`          TINYINT(1)        DEFAULT NULL,
  `m4_remarks`            TEXT              DEFAULT NULL,
  `operator_sign`         VARCHAR(100)      DEFAULT NULL,
  `chemist_sign`          VARCHAR(100)      DEFAULT NULL,
  `section_head_sign`     VARCHAR(100)      DEFAULT NULL,
  `timestamp`             TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `prod_pan_logbook` (
  `id`                    INT           NOT NULL AUTO_INCREMENT,
  `Date`                  DATE              DEFAULT NULL,
  `season`                VARCHAR(20)       DEFAULT NULL,
  `grade`                 VARCHAR(30)       DEFAULT NULL,
  `strike_no`             VARCHAR(20)       DEFAULT NULL,
  `pan_no`                VARCHAR(10)       DEFAULT NULL,
  `start_time`            VARCHAR(10)       DEFAULT NULL,
  `drop_time`             VARCHAR(10)       DEFAULT NULL,
  `boil_time`             VARCHAR(20)       DEFAULT NULL,
  `down_time`             VARCHAR(20)       DEFAULT NULL,
  `qty`                   VARCHAR(20)       DEFAULT NULL,
  `cry_no`                VARCHAR(20)       DEFAULT NULL,
  `sample_purity`         VARCHAR(20)       DEFAULT NULL,
  `brix`                  VARCHAR(20)       DEFAULT NULL,
  `purity`                VARCHAR(20)       DEFAULT NULL,
  `remarks`               TEXT              DEFAULT NULL,
  `timestamp`             TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `prod_decanter` (
  `id`                    INT           NOT NULL AUTO_INCREMENT,
  `Date`                  DATE              DEFAULT NULL,
  `season`                VARCHAR(20)       DEFAULT NULL,
  `crop_day`              VARCHAR(10)       DEFAULT NULL,
  `time_slot`             VARCHAR(20)       DEFAULT NULL,
  `st1_mud`               DECIMAL(8,2)      DEFAULT NULL,
  `st1_centrate`          DECIMAL(8,2)      DEFAULT NULL,
  `st1_floc`              DECIMAL(8,2)      DEFAULT NULL,
  `st1_water`             DECIMAL(8,2)      DEFAULT NULL,
  `st1_load`              DECIMAL(8,2)      DEFAULT NULL,
  `st1_torque`            DECIMAL(8,2)      DEFAULT NULL,
  `st1_vib`               DECIMAL(8,2)      DEFAULT NULL,
  `st1_diff_speed`        DECIMAL(8,2)      DEFAULT NULL,
  `st2_mud`               DECIMAL(8,2)      DEFAULT NULL,
  `st2_centrate`          DECIMAL(8,2)      DEFAULT NULL,
  `st2_floc`              DECIMAL(8,2)      DEFAULT NULL,
  `st2_water`             DECIMAL(8,2)      DEFAULT NULL,
  `st2_load`              DECIMAL(8,2)      DEFAULT NULL,
  `st2_torque`            DECIMAL(8,2)      DEFAULT NULL,
  `st2_vib`               DECIMAL(8,2)      DEFAULT NULL,
  `st2_diff_speed`        DECIMAL(8,2)      DEFAULT NULL,
  `timestamp`             TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `prod_clarification` (
  `id`                    INT           NOT NULL AUTO_INCREMENT,
  `Date`                  DATE              DEFAULT NULL,
  `season`                VARCHAR(20)       DEFAULT NULL,
  `crop_day`              VARCHAR(10)       DEFAULT NULL,
  `inst_hod`              TEXT              DEFAULT NULL,
  `inst_dy_hod`           TEXT              DEFAULT NULL,
  `inst_sectional_head`   TEXT              DEFAULT NULL,
  `time_slot`             VARCHAR(20)       DEFAULT NULL,
  `juice_flow`            DECIMAL(8,2)      DEFAULT NULL,
  `mol_dose`              DECIMAL(8,3)      DEFAULT NULL,
  `mol_set_be`            DECIMAL(8,2)      DEFAULT NULL,
  `mol_std_wt`            DECIMAL(8,2)      DEFAULT NULL,
  `mol_meas_be`           DECIMAL(8,2)      DEFAULT NULL,
  `mol_meas_wt`           DECIMAL(8,2)      DEFAULT NULL,
  `vessel_std_time`       DECIMAL(8,2)      DEFAULT NULL,
  `vessel_meas_time`      DECIMAL(8,2)      DEFAULT NULL,
  `ph_pre`                DECIMAL(5,2)      DEFAULT NULL,
  `ph_shock`              DECIMAL(5,2)      DEFAULT NULL,
  `ph_sulphured`          DECIMAL(5,2)      DEFAULT NULL,
  `sulphur_temp`          DECIMAL(8,2)      DEFAULT NULL,
  `boiler_temp`           DECIMAL(8,2)      DEFAULT NULL,
  `boiler_press`          DECIMAL(8,2)      DEFAULT NULL,
  `op_sign`               VARCHAR(100)      DEFAULT NULL,
  `chem_sign`             VARCHAR(100)      DEFAULT NULL,
  `remarks`               TEXT              DEFAULT NULL,
  `timestamp`             TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
